from typing import List

import pandas as pd
import numpy as np


def load_gold_shifted_labels(path: str) -> pd.DataFrame:
    """ Read labels generated by Dmitrii and convert them in pandas DataFrame

    :param path: path to the .csv file for reading
    :return: pd.DataFrame with columns:
                filename
                timestamp
                label_value (arousal or valence)
    """
    # read csv file, first row is trash
    labels_dataframe = pd.read_csv(path, header=None, skiprows=1)
    # split first column in format to two columns filename and timestamp
    # example SEM1002_0.02 -> filename:SEM1002 timestamp:0.02
    labels_dataframe[['filename', 'timestamp']] = labels_dataframe.iloc[:, 0].str.split("_", expand=True)
    # convert timestamp in float
    labels_dataframe['timestamp'] = labels_dataframe['timestamp'].astype('float32')
    # del first row to clear memory
    del labels_dataframe[0]
    # rename columns for convenient use and rearrange them
    labels_dataframe.columns = ['label_value', 'filename', 'timestamp']
    labels_dataframe = labels_dataframe[['filename', 'timestamp', 'label_value']]

    return labels_dataframe


def split_labels_dataframe_according_filenames(label_dataframe:pd.DataFrame) -> List[pd.DataFrame]:
    """ Split labels located in DataFrame according their filename on different DataFrames

    :param label_dataframe: DataFrame with labels with columns:
                                      filename
                                      timestamp
                                      label_value (arousal or valence)
    :return: list of split DataFrames
    """
    # create resulting variable
    dataframes_list=[]
    # extract unique filenames from "filename" column
    filenames=label_dataframe['filename'].unique()
    #split DataFrame according filenames and append split DataFrames to resulting list
    for filename in filenames:
        filename_dataframe=label_dataframe[label_dataframe['filename']==filename]
        dataframes_list.append(filename_dataframe)
    return dataframes_list


if __name__=="main":
    # you can test functions here
    # specify path to file
    path = r"E:\Databases\SEMAINE\SEM_labels_arousal_100Hz_gold_shifted.csv"
    # data should be DataFrame with columns ['filename', 'timestamp', 'label_value']
    data = load_gold_shifted_labels(path)
    # dataframes should be list of DataFrames [pd.DataFrame,...]
    # each with columns ['filename', 'timestamp', 'label_value']
    dataframes=split_labels_dataframe_according_filenames(data)
    print(dataframes)
