from typing import List

import pandas as pd
import numpy as np


def read_gold_shifted_labels(path: str) -> pd.DataFrame:
    """ Read labels generated by Dmitrii and convert them in pandas DataFrame

    :param path: path to the .csv file for reading
    :return: pd.DataFrame with columns:
                filename
                timestamp
                label_value (arousal or valence)
    """
    # read csv file, first row is trash
    labels_dataframe = pd.read_csv(path, header=None, skiprows=1)
    # split first column in format to two columns filename and timestamp
    # example SEM1002_0.02 -> filename:SEM1002 timestamp:0.02
    labels_dataframe[['filename', 'timestamp']] = labels_dataframe.iloc[:, 0].str.split("_", expand=True)
    # convert timestamp in float
    labels_dataframe['timestamp'] = labels_dataframe['timestamp'].astype('float32')
    # del first row to clear memory
    del labels_dataframe[0]
    # rename columns for convenient use and rearrange them
    labels_dataframe.columns = ['label_value', 'filename', 'timestamp']
    labels_dataframe = labels_dataframe[['filename', 'timestamp', 'label_value']]

    return labels_dataframe


def split_labels_dataframe_according_filenames(label_dataframe:pd.DataFrame) -> List[pd.DataFrame,...]:
    """

    :param label_dataframe:
    :return:
    """
    dataframes_list=[]


path = r"E:\Databases\SEMAINE\SEM_labels_arousal_100Hz_gold_shifted.csv"

data = read_gold_shifted_labels(path)
